### ISSUE TITLE
Anthrocon registration target date is October 19

### ISSUE THREAD

**Issue by UncleKage** [Anthrocon-Reg/ubersystem#92]
Are we ready to go?  If not, what more is needed from us?  I'd like to start looking over the system to make sure we remembered to add all the things we forgot to mention last year!

**Comment by TheSonicGod** [comment]
I do have to work on that day, but I'll be up around 1000 and check the system.

**Comment by kitsuta** [comment]
This date is still doable, but it won't give you guys much time to look over the system before it launches - and due to unfortunate timing, I won't be available to help make sure the launch goes smoothly. I propose we push back the actual launch date to this Friday instead, with a "feature complete" system ready by the end of tomorrow for review.
